// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'IMdi:accountBoxMultiple': typeof import('~icons/mdi/account-box-multiple')['default']
    'IMdi:alertBoxOutline': typeof import('~icons/mdi/alert-box-outline')['default']
    'IMdi:earth': typeof import('~icons/mdi/earth')['default']
    'IMdi:hammerSickle': typeof import('~icons/mdi/hammer-sickle')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NSpace: typeof import('naive-ui')['NSpace']
  }
}

export { }
